server.port=8082
# Batch interval in milliseconds (configurable)
notification.batch.interval=30000
# URL of notification service
notification.service.url=http://localhost:8000

notification.sms.enabled=true
notification.sms.provider=mock

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sskhot104@gmail.com
spring.mail.password=pjfxvdyfvmjfandf

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=20000
spring.mail.properties.mail.smtp.timeout=20000
spring.mail.properties.mail.smtp.writetimeout=20000

#spring.mail.properties.mail.smtp.localhost=localhost